export const ADD_USER = 'ADD_USER'
export const UPDATE_USERNAME = 'UPDATE_USERNAME'
export const DELETE_USER = 'DELETE_USER'
export const DELETE_USERS = 'DELETE_USERS'

export const CHANGE_THEME = 'CHANGE_THEME'